const UserActions = {
    USER_PROFILE:"USER_PROFILE",
    CLEAR_USER_PROFILE:"CLEAR_USER_PROFILE",
    USER_REPOS:"USER_REPOS",
    LINECHART_DATA:"LINECHART_DATA",
    COLUMNCHART_DATA:"COLUMNCHART_DATA"
}

export default UserActions;